### ISSUE TITLE
pre-populate some prefixes?

### ISSUE THREAD

**Issue by ahs3** [UEFI/DSD-Guide#10]
Would it make sense to pre-populate this document with vendor prefixes from PNP and/or ACPI IDs?  For now, I assume "no" since a vendor may want to use something different.

Other thoughts?

**Comment by samerhaj** [comment]
what about "linux-"? Maybe ask the Linux community?

**Comment by ahs3** [comment]
Yeah, "linux-" could be a useful one.  I'd prefer to avoid OS-specific ones, if we can, though.

I'm mostly thinking that there are all of these PNP and ACPI IDs are already out there in the world, and it seemed kind of silly to create a whole new set of IDs.  But maybe that's presumptuous, too.

So maybe what we should do is wait and see what gets asked for, and go from there?

**Comment by ahs3** [comment]
Closing this issue for now.  If demand is suffiicient, we may pre-populate prefixes in the future but that does not seem to be an issue yet.
