### ISSUE TITLE
Add Buffer to Data Format Definition of Device Properties 

### ISSUE THREAD

**Issue by rgough71** [UEFI/DSD-Guide#17]
The current definition for Device Properties does not list Buffer as a supported data type.
For some device types, it would be advantageous to support buffers as a property value.
Can Buffer be added to the list of supported data types?

**Comment by saurinshah9** [comment]
> The current definition for Device Properties does not list Buffer as a supported data type. For some device types, it would be advantageous to support buffers as a property value. Can Buffer be added to the list of supported data types?

Next generation of audio devices would benefit greatly if Buffer data type were a supported data type to describe some of the audio device properties. None of the existing data types can be used to describe these properties as they will make software overly complex.

**Comment by rafaeljw** [comment]
Changing the Device Properties would require updating the property parsing code in the Linux kernel which does not cover the case of the property value being a buffer.

In my view, the cleanest way to address this would be to introduce a new UUID for _DSD with a new format definition in which the Data Structure would be a package of 2 elements: the key (a string) and the data being a buffer or a path to an object that evaluates to a buffer (either a Name () or a Method ()).

**Comment by saurinshah9** [comment]
Based on these discussions, we defined new UUID (edb12dd0-363d-4085-a3d2-49522ca160c4) and made following changes:

Name(_DSD, Package() {
    ToUUID("daffd814-6eba-4d8c-8a91-bc9bbf4aa301"),
    Package () {
        Package (2) {"property-integer", 2},
    },
    ToUUID("edb12dd0-363d-4085-a3d2-49522ca160c4"),
    Package() {
        Package (2) {"property-buffer", "BUF1"},
    }
}) //End _DSD

Name(BUF1, Buffer() {
    0x03, 0x00, 0x01, 0x00,
    0xFF, 0xFF, 0x00, 0x00,
    0xFF, 0xFF, 0x00, 0x00,
    0x10, 0x00, 0x00, 0x00,
}) //End BUF1

If this looks good to everyone, can we make the change?

**Comment by saurinshah9** [comment]
I have created Pull Request for this change: https://github.com/UEFI/DSD-Guide/pull/18

**Comment by samerhaj** [comment]
The new Pull Request is https://github.com/UEFI/DSD-Guide/pull/19/ 

Please review
