### ISSUE TITLE
"Debug Trace Graph" figure missing

### ISSUE THREAD

**Issue by samerhaj** [UEFI/DSD-Guide#8]
The "Debug Trace Graph" is supposed to be at https://github.com/samerhaj/DSD-Guide/raw/main/fig1.png is missing from the md and rst versions, but shows up in the pdf

**Comment by ahs3** [comment]
Interesting.  fig2.png does not show up in the PDF but it should.  I found several other oddities like that where conversion was the problem, so i had to futz around with the asiidoc so the converters would not get confused.

in the case of the images, the specific problem was the .md and .rst files have pointers to a file name; i've added the .png files to the 'make install" step.
